import { Calculator, Clock, Hash } from "lucide-react";
import Image from "next/image";

export const TOOLS = [
  {
    category: "YouTube",
    href: "/tools/youtube-shorts-title-generator",
    icon: <Image src="/icons/youtube-short.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Title Generator",
    description: "Generate 10 click-worthy YouTube Shorts titles in seconds. Powered by AI optimized for the 2025 algorithm.",
    cta: "Generate titles",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-caption-generator",
    icon: (
      <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />
    ),
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Caption Generator",
    description: "Create viral TikTok captions with perfectly targeted hashtags. Enter your video topic and get a ready-to-paste caption.",
    cta: "Generate captions",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-thumbnail-prompt-generator",
    icon: <Image src="/icons/youtube.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Thumbnail Prompt Generator",
    description: "Get AI image prompts for your YouTube thumbnail optimized for Midjourney, DALL·E 3, and Stable Diffusion.",
    cta: "Generate prompts",
  },

  {
    category: "YouTube",
    href: "/tools/youtube-shorts-script-generator",
    icon: <Image src="/icons/youtube-short.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Script Generator",
    description: "Write a complete Short script hook, body, and CTA in seconds. AI-powered, conversational, optimized for high retention.",
    cta: "Generate script",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-shorts-duration-calculator",
    icon: <Image src="/icons/youtube-short.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Duration Calculator",
    description: "Find out how many Shorts you can make from any video and which clip length performs best for your content type.",
    cta: "Calculate duration",
  },
  {
    category: "All Platforms",
    href: "/tools/hashtag-generator",
    icon: <Hash size={22} className="text-violet-500" />,
    badge: "All Platforms",
    badgeColor: "bg-violet-50 text-violet-600 border-violet-100",
    title: "Hashtag Generator",
    description: "Generate the best hashtags for Instagram, TikTok, and YouTube Shorts. AI-powered, platform-specific hashtag sets in seconds.",
    cta: "Generate hashtags",
  },
  {
    category: "Instagram",
    href: "/tools/best-time-to-post-instagram-reels",
    icon: <Clock size={22} className="text-pink-600" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Best Time to Post Instagram Reels",
    description: "Find the best time to post Reels today by weekday and timezone. Built for Instagram creators planning high-engagement posts.",
    cta: "Find best times",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-size-calculator",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Size Calculator",
    description: "Check Reels dimensions, 9:16 aspect ratio, 1080x1920 export size, and safe zones before uploading.",
    cta: "Calculate size",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-length-calculator",
    icon: <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Length Calculator",
    description: "See how long Instagram Reels can be and whether your duration is ideal for retention and discovery.",
    cta: "Check length",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-trending-songs-finder",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Trending Songs Finder",
    description: "Find trending songs on Instagram Reels today with an audio research checklist and trend scoring tool.",
    cta: "Find songs",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-history-finder",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels History Finder",
    description: "Learn how to find recently watched Reels, liked Reels, pause Reels, and fix common Reels problems.",
    cta: "Find Reels",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-trial-reels-guide",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Trial Reels Guide",
    description: "Understand what Trial Reels are and decide whether to test a Reel with non-followers before posting normally.",
    cta: "Try the guide",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-monetization-checker",
    icon: <Image src="/icons/youtube.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube",
    badgeColor: "bg-emerald-50 text-emerald-600 border-emerald-100",
    title: "YouTube Monetization Checker",
    description: "Check if any YouTube channel meets the YPP requirements. See subscriber count, video count, and eligibility status instantly.",
    cta: "Check eligibility",
  },
  {
    category: "All Platforms",
    href: "/tools/video-aspect-ratio-calculator",
    icon: <Calculator size={22} className="text-slate-500" />,
    badge: "All Platforms",
    badgeColor: "bg-slate-50 text-slate-600 border-slate-200",
    title: "Video Aspect Ratio Calculator",
    description: "Instantly simplify any video ratio, convert between sizes, and find the correct dimensions for every social platform.",
    cta: "Calculate ratio",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-coins-calculator",
    icon: <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Coins to USD Calculator",
    description: "Convert TikTok coins to USD value instantly. Calculate coin costs or creator payouts based on latest 2025 rates.",
    cta: "Calculate value",
  },
  {
    category: "TikTok",
    href: "/tools/best-time-to-post-on-tiktok",
    icon: <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Best Time to Post on TikTok",
    description: "Find the peak activity hours for your TikTok audience in 2025. Optimized for your specific timezone.",
    cta: "Find best times",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-video-downloader",
    icon:  <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Video Download Helper",
    description: "Try a free best-effort TikTok download helper, with clear fallback steps when public extraction services are unavailable.",
    cta: "Try helper",
  },
];

export const TOOL_CATEGORIES = [
  {
    name: "Instagram",
    title: "Instagram Reels Tools",
    description: "Plan, format, and troubleshoot Reels with tools built around your Instagram keyword research.",
  },
  {
    name: "TikTok",
    title: "TikTok Tools",
    description: "Caption, timing, downloader, and coin tools for short-form TikTok workflows.",
  },
  {
    name: "YouTube",
    title: "YouTube Tools",
    description: "Shorts titles, scripts, thumbnails, duration planning, and monetization checks.",
  },
  {
    name: "All Platforms",
    title: "All-Platform Tools",
    description: "Reusable creator utilities for hashtags and video sizing across every short-form platform.",
  },
];
