import { Calculator, Captions, Clock, Film, Hash, Scissors } from "lucide-react";
import Image from "next/image";

export const TOOLS = [
  {
    category: "YouTube",
    href: "/tools/youtube-shorts-title-generator",
    icon: <Image src="/icons/youtube-short.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Title Generator",
    description: "Generate 10 click-worthy YouTube Shorts titles in seconds. Powered by AI optimized for the 2025 algorithm.",
    cta: "Generate titles",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-caption-generator",
    icon: (
      <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />
    ),
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Caption Generator",
    description: "Create viral TikTok captions with perfectly targeted hashtags. Enter your video topic and get a ready-to-paste caption.",
    cta: "Generate captions",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-thumbnail-prompt-generator",
    icon: <Image src="/icons/youtube.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Thumbnail Prompt Generator",
    description: "Get AI image prompts for your YouTube thumbnail optimized for Midjourney, DALL·E 3, and Stable Diffusion.",
    cta: "Generate prompts",
  },

  {
    category: "YouTube",
    href: "/tools/youtube-shorts-script-generator",
    icon: <Image src="/icons/youtube-short.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Script Generator",
    description: "Write a complete Short script hook, body, and CTA in seconds. AI-powered, conversational, optimized for high retention.",
    cta: "Generate script",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-shorts-duration-calculator",
    icon: <Image src="/icons/youtube-short.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Duration Calculator",
    description: "Find out how many Shorts you can make from any video and which clip length performs best for your content type.",
    cta: "Calculate duration",
  },
  {
    category: "All Platforms",
    href: "/tools/hashtag-generator",
    icon: <Hash size={22} className="text-violet-500" />,
    badge: "All Platforms",
    badgeColor: "bg-violet-50 text-violet-600 border-violet-100",
    title: "Hashtag Generator",
    description: "Generate the best hashtags for Instagram, TikTok, and YouTube Shorts. AI-powered, platform-specific hashtag sets in seconds.",
    cta: "Generate hashtags",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-video-downloader",
    icon: <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Video Download Helper",
    description: "Try a free best-effort Instagram download helper, with clear fallback steps when public extraction services are unavailable.",
    cta: "Try helper",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-bio-generator",
    icon: <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Bio Generator",
    description: "Generate 5 ready-to-use Instagram bio options aesthetic, funny, professional, minimal, and bold in seconds.",
    cta: "Generate bios",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-story-size-calculator",
    icon: <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Story Size Calculator",
    description: "Check Story dimensions, 9:16 aspect ratio, 1080x1920 export size, and safe zones before posting.",
    cta: "Calculate size",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-story-idea-generator",
    icon: <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Story Idea Generator",
    description: "Generate 8 engaging Story ideas with poll, quiz, and sticker suggestions tailored to your niche.",
    cta: "Generate ideas",
  },
  {
    category: "Instagram",
    href: "/tools/best-time-to-post-instagram-reels",
    icon: <Clock size={22} className="text-pink-600" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Best Time to Post Instagram Reels",
    description: "Find the best time to post Reels today by weekday and timezone. Built for Instagram creators planning high-engagement posts.",
    cta: "Find best times",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-size-calculator",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Size Calculator",
    description: "Check Reels dimensions, 9:16 aspect ratio, 1080x1920 export size, and safe zones before uploading.",
    cta: "Calculate size",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-safe-zone-checker",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Safe Zone Checker",
    description: "Calculate safe zones for Reels captions, logos, faces, and product text so Instagram UI does not cover them.",
    cta: "Check safe zone",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-caption-length-checker",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Caption Length Checker",
    description: "Count caption characters, words, hashtags, and lines before posting your next Instagram Reel.",
    cta: "Check caption",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-cover-size-calculator",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Cover Size Calculator",
    description: "Calculate Reels cover, feed preview, profile grid crop, and title placement sizes.",
    cta: "Calculate cover",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-length-calculator",
    icon: <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels Length Calculator",
    description: "See how long Instagram Reels can be and whether your duration is ideal for retention and discovery.",
    cta: "Check length",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-trending-songs-finder",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Trending Songs Finder",
    description: "Find trending songs on Instagram Reels today with an audio research checklist and trend scoring tool.",
    cta: "Find songs",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-reels-history-finder",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Reels History Finder",
    description: "Learn how to find recently watched Reels, liked Reels, pause Reels, and fix common Reels problems.",
    cta: "Find Reels",
  },
  {
    category: "Instagram",
    href: "/tools/instagram-trial-reels-guide",
    icon:  <Image src="/icons/instagram.png" alt="Instagram" width={22} height={22} className="object-contain" />,
    badge: "Instagram",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Instagram Trial Reels Guide",
    description: "Understand what Trial Reels are and decide whether to test a Reel with non-followers before posting normally.",
    cta: "Try the guide",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-monetization-checker",
    icon: <Image src="/icons/youtube.png" alt="Youtube" width={22} height={22} className="text-red-500" />,
    badge: "YouTube",
    badgeColor: "bg-emerald-50 text-emerald-600 border-emerald-100",
    title: "YouTube Monetization Checker",
    description: "Check if any YouTube channel meets the YPP requirements. See subscriber count, video count, and eligibility status instantly.",
    cta: "Check eligibility",
  },
  {
    category: "YouTube",
    href: "/tools/youtube-shorts-title-length-checker",
    icon: <Image src="/icons/youtube-short.png" alt="YouTube Shorts" width={22} height={22} className="object-contain" />,
    badge: "YouTube Shorts",
    badgeColor: "bg-red-50 text-red-600 border-red-100",
    title: "YouTube Shorts Title Length Checker",
    description: "Check Shorts title characters, word count, and mobile readability before uploading.",
    cta: "Check title",
  },
  {
    category: "All Platforms",
    href: "/tools/video-aspect-ratio-calculator",
    icon: <Calculator size={22} className="text-slate-500" />,
    badge: "All Platforms",
    badgeColor: "bg-slate-50 text-slate-600 border-slate-200",
    title: "Video Aspect Ratio Calculator",
    description: "Instantly simplify any video ratio, convert between sizes, and find the correct dimensions for every social platform.",
    cta: "Calculate ratio",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-coins-calculator",
    icon: <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Coins to USD Calculator",
    description: "Convert TikTok coins to USD value instantly. Calculate coin costs or creator payouts based on latest 2025 rates.",
    cta: "Calculate value",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-caption-character-counter",
    icon: <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Caption Character Counter",
    description: "Count TikTok caption characters, words, hashtags, and mentions before posting.",
    cta: "Count caption",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-hashtag-counter",
    icon: <Hash size={22} className="text-pink-600" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Hashtag Counter",
    description: "Count TikTok hashtags, detect duplicates, and keep your hashtag mix focused.",
    cta: "Count hashtags",
  },
  {
    category: "TikTok",
    href: "/tools/best-time-to-post-on-tiktok",
    icon: <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "Best Time to Post on TikTok",
    description: "Find the peak activity hours for your TikTok audience in 2025. Optimized for your specific timezone.",
    cta: "Find best times",
  },
  {
    category: "Facebook",
    href: "/tools/facebook-video-downloader",
    icon: <Image src="/icons/facebook.png" alt="Facebook" width={22} height={22} className="object-contain" />,
    badge: "Facebook",
    badgeColor: "bg-blue-50 text-blue-600 border-blue-100",
    title: "Facebook Video Download Helper",
    description: "Try a free best-effort Facebook download helper, with clear fallback steps when public extraction services are unavailable.",
    cta: "Try helper",
  },
  {
    category: "All Platforms",
    href: "/tools/video-subtitle-generator",
    icon: <Captions size={22} className="text-slate-500" />,
    badge: "All Platforms",
    badgeColor: "bg-slate-50 text-slate-600 border-slate-200",
    title: "Video Subtitle Generator",
    description: "Get accurate AI captions for your video in seconds. Free SRT and VTT download for clips up to 2 minutes.",
    cta: "Generate subtitles",
  },
  {
    category: "All Platforms",
    href: "/tools/video-trimmer",
    icon: <Scissors size={22} className="text-slate-500" />,
    badge: "All Platforms",
    badgeColor: "bg-slate-50 text-slate-600 border-slate-200",
    title: "Video Trimmer",
    description: "Cut a video to the exact clip you need, right in your browser. No upload, no watermark, no sign-up.",
    cta: "Trim video",
  },
  {
    category: "All Platforms",
    href: "/tools/video-to-gif-converter",
    icon: <Film size={22} className="text-slate-500" />,
    badge: "All Platforms",
    badgeColor: "bg-slate-50 text-slate-600 border-slate-200",
    title: "Video to GIF Converter",
    description: "Turn any video clip into a shareable GIF, right in your browser. No upload, no watermark, no sign-up.",
    cta: "Convert to GIF",
  },
  {
    category: "TikTok",
    href: "/tools/tiktok-video-downloader",
    icon:  <Image src="/icons/tik-tok.png" alt="TikTok" width={22} height={22} className="object-contain" />,
    badge: "TikTok",
    badgeColor: "bg-pink-50 text-pink-600 border-pink-100",
    title: "TikTok Video Download Helper",
    description: "Try a free best-effort TikTok download helper, with clear fallback steps when public extraction services are unavailable.",
    cta: "Try helper",
  },
];

export const TOOL_CATEGORIES = [
  {
    name: "Instagram",
    title: "Instagram Reels Tools",
    description: "Plan, format, and troubleshoot Reels with tools built around your Instagram keyword research.",
  },
  {
    name: "TikTok",
    title: "TikTok Tools",
    description: "Caption, timing, downloader, and coin tools for short-form TikTok workflows.",
  },
  {
    name: "YouTube",
    title: "YouTube Tools",
    description: "Shorts titles, scripts, thumbnails, duration planning, and monetization checks.",
  },
  {
    name: "Facebook",
    title: "Facebook Tools",
    description: "Download helper for Facebook videos, Reels, and Watch posts.",
  },
  {
    name: "All Platforms",
    title: "All-Platform Tools",
    description: "Reusable creator utilities for hashtags and video sizing across every short-form platform.",
  },
];
